version: '3.9'
services:
  dbMysql:
    container_name: dbMysql
    image: $DB_MYSQL_IMAGE
    ports:
      - 3306:3306
    volumes:
      - ./dbMysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_MYSQL_DATABASE
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_ROOT_PASSWORD

  dbPostgres:
    container_name: dbPostgres
    image: $DB_POSTGRES_IMAGE
    ports:
      - 5432:5432
    volumes:
      - ./dbPostgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_POSTGRES_PASSWORD
      POSTGRES_USER: $DB_POSTGRES_USER
      POSTGRES_DB: $DB_POSTGRES_DATABASE
